server:
  port: 9004

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: seata
    password: seata

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  hystrix:
    enabled: false

mybatis:
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    io:
      seata: info
